#pragma once
#define FORCE_NKRO
#define ENABLE_COMPILE_KEYCODE
#define ONESHOT_TIMEOUT 2500
#define TAPPING_TERM 300 //default
#define TAPPING_TERM_PER_KEY
#define TAP_DANCE_DOUBLE_TAP_TERM 250
//#define LEADER_TIMEOUT 1000
//#define TAPPING_TOGGLE 3
