#pragma once
#define FORCE_NKRO
#define ENABLE_COMPILE_KEYCODE
#define DOUBLE_TAP_SHIFT_TURNS_ON_CAPS_WORD
#define CAPS_WORD_IDLE_TIMEOUT 3000
#define ONESHOT_TIMEOUT 2500
//#define TAPPING_TERM 200
//#define LEADER_TIMEOUT 1000
//#define TAPPING_TOGGLE 3
